version: '2'

services:

  application:
    container_name: app
    image: tianon/true
    volumes:
      - ./laravel:/var/www/html
    networks: []

  php-fpm:
    container_name: app-php-fpm
    build:
      context: .
      dockerfile: php-fpm.Dockerfile
    environment:
      - DB_HOST=app-mysql
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes_from:
      - application
    networks: 
      - back

  nginx:
    container_name: app-nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_EXTERNAL_HTTP_PORT}:80"
    depends_on:
      - php-fpm
    networks: 
      - front
      - back

  mysql:
    container_name: app-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    networks: 
      - back

networks: 
  front:
    external:
      name: front
  back:
    external:
      name: back

volumes:
  mysql:
    external:
      name: sample-mysql